// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBXBTCY8DZpmw-sZ7wZkFV0UIqqWf2QgOk',
    appId: '1:672123118975:web:767453f65255ee284d664a',
    messagingSenderId: '672123118975',
    projectId: 'fittl-1cbcc',
    authDomain: 'fittl-1cbcc.firebaseapp.com',
    storageBucket: 'fittl-1cbcc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYWwK0N3AZRVXc7WevcYHw7oLKy4WAMvs',
    appId: '1:672123118975:android:64d0d9f56e5c84d74d664a',
    messagingSenderId: '672123118975',
    projectId: 'fittl-1cbcc',
    storageBucket: 'fittl-1cbcc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCfT0OwFGWrUXcpK-LoLU_8rJmPrjZ7kK8',
    appId: '1:672123118975:ios:29b73b4cd4450a474d664a',
    messagingSenderId: '672123118975',
    projectId: 'fittl-1cbcc',
    storageBucket: 'fittl-1cbcc.appspot.com',
    iosClientId: '672123118975-k8d9v8offmte95e9o1r44haoma4d4rdm.apps.googleusercontent.com',
    iosBundleId: 'com.example.dartCode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCfT0OwFGWrUXcpK-LoLU_8rJmPrjZ7kK8',
    appId: '1:672123118975:ios:5ed136a1d9b9d3c74d664a',
    messagingSenderId: '672123118975',
    projectId: 'fittl-1cbcc',
    storageBucket: 'fittl-1cbcc.appspot.com',
    iosClientId: '672123118975-unmkqf5gh1aj2s9sqhub2ung5inq5gcr.apps.googleusercontent.com',
    iosBundleId: 'com.teamvier.fittl',
  );
}
